title: Dening Zhang's Homepage
page-top-title: Dening Zhang
top-section-bg-text: Computer Science
home-subtitle: Dening Zhang&ensp;|&ensp;张德宁
copyright-text: '&copy; Dening Zhang 2023-2024. All Rights Reserved.'
