title: De-ning Zhang's Homepage
page-top-title: De-ning Zhang
top-section-bg-text: Computer Science
home-subtitle: De-ning Zhang&ensp;|&ensp;张德宁
copyright-text: '&copy; De-ning Zhang 2023-2024. All Rights Reserved.'
